[build]
  command = "npm run build"
  publish = "dist/angular-ssr-app"
  
[functions]
  directory = "dist/angular-ssr-app/server"
  node_bundler = "esbuild"
  included_files = ["dist/angular-ssr-app/server/*.mjs"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200